### ISSUE TITLE
Connect to a running ptvsd session

### ISSUE THREAD

**Issue by clawdelle** [emacs-lsp/dap-mode#93] opened 2019-06-11 14:08 UTC
Hi,
I would like to debug a python script for Blender 3D. Blender starts a ptvsd server with port 5678. How can I connect to this port? I have no idea about Lisp but would like to use emacs / spacemacs.

**Comment by yyoncho** [comment] 2019-06-11 15:50
Duplicate of https://github.com/emacs-lsp/dap-mode/issues/67 (cc @f279801 )

**Closed by yyoncho** 2019-06-11 15:50 UTC
