### ISSUE TITLE
Wrong number of arguments

### ISSUE THREAD

**Issue by MiyamotoAkira** [emacs-lsp/dap-mode#315] opened 2020-07-09 12:47 UTC
Hi,

I just installed the latest version from Melpa (20200707.1837), and I got the following error:
`run-hooks: Wrong number of arguments (1 . 1), 0`

This happens when I use [perspective](https://github.com/nex3/perspective-el) to create a new perspective (using the function `persp-switch`)

**Comment by ericdallo** [comment] 2020-07-09 12:52
@MiyamotoAkira Could you please <kbd>M-x</kbd> `toggle-debug-on-error`, reproduce it again and paste the stacktrace here?

**Comment by MiyamotoAkira** [comment] 2020-07-09 13:03
Well, I have learned a command to investigate issues :-)

```
Debugger entered--Lisp error: (wrong-number-of-arguments (1 . 1) 0)
  treemacs--remove-treemacs-window-in-new-frames()
  run-hooks(persp-activated-hook)
  persp-activate(#s(perspective :name ".emacs.d" :buffers (#<buffer *Backtrace*>) :killed nil :local-variables nil :last-switch-time (24327 5174 809078 470000) :created-time (24327 5174 809080 758000) :window-configuration #<window-configuration> :point-marker #<marker at 77 in *GNU Emacs*>))
  persp-switch(".emacs.d" norecord)
  persp-new(".emacs.d")
  persp-switch(nil)
  funcall-interactively(persp-switch nil)
  call-interactively(persp-switch nil nil)
  command-execute(persp-switch)
```

**Comment by ericdallo** [comment] 2020-07-09 13:50
Yes, the trace helps a lot :)
This seems to be a bug on [treemacs](https://github.com/Alexander-Miller/treemacs), I suggest you open an issue there and link it here

**Comment by nbfalcon** [comment] 2020-09-10 17:52
Fixed in upstream.

**Closed by nbfalcon** 2020-09-10 17:52 UTC
