### ISSUE TITLE
dap debugging is constantly opening new windows : possible to stop this?

### ISSUE THREAD

**Issue by rileyrg** [emacs-lsp/dap-mode#170] opened 2019-12-12 16:17 UTC
I constantly find myself having to hit C-x 1 to limit my windows to the current window but this isn't really what I want since it closes the locals and hydra too. Can I tell emacs or dap-mode to ONLY have ONE PHP window open? As I step between different files it's opening a new window and leaving it open when I return to another file in the debug stack. I'm rapidly running out of screen real estate. Possibly there's a way in basic emacs to configure only one window of a certain mode eh PHP in my case?

**Comment by yyoncho** [comment] 2019-12-12 16:46
Can you describe the scenarios in which you get redundant window? Unfortunately, there is no way to enforce that behaviour and we should fix case by case.

**Comment by rileyrg** [comment] 2019-12-13 08:32
It's pretty easy, step into any function that exists in a different source file. Step out and it stays open. I've turned off the output window via dap-auto-show-output and that helps a little but ideally, I would like an option to have only ONE debug *source* window. The stack allows me to to easily switch around should I want to. Admittedly I use a relatively small laptop so it's more important to conserve real estate. 
![Screenshot from 2019-12-13 09-09-31](https://user-images.githubusercontent.com/362891/70785732-6592ca80-1d8b-11ea-8185-81b1a6bd7db6.png)

**Comment by yyoncho** [comment] 2019-12-13 17:27
Pushed a fix, let me know if it works for you. I was unable to reproduce the bug on my side but this commit will probably fix it.

**Closed** 2019-12-13 17:26 UTC

**Comment by rileyrg** [comment] 2019-12-14 08:55
Hi, single window works now. Thank you. But PHP Debug Output is still opening when I kick of a debug session when it breaks despite me setting the option dap-auto-show-output to nil  to nil.
