### ISSUE TITLE
Warning (emacs): Initialize request failed: Failed to load MI Debugger

### ISSUE THREAD

**Issue by LinArcX** [emacs-lsp/dap-mode#80] opened 2019-04-29 16:02 UTC
Hi. i want to debug c/c++ app in emacs via dap-mode, so i follow:
https://github.com/emacs-lsp/dap-mode/blob/3bfbaf11493b884f9748a1007ed21805b01de8b9/README.org#native-debug-gdblldb

This is my init.el:
https://github.com/LinArcX/Blogit/blob/master/Packages/Emacs/init.el

After running `dap-debug` i get these error:
Flymake log:
```
Error [flymake-proc test.cpp]: NOMK: No buildfile (Makefile) found for /home/linarcx/temp/cpp/test.cpp
Warning [flymake test.cpp]: Disabling backend flymake-proc-legacy-flymake because NOMK: No buildfile (Makefile) found for /home/linarcx/temp/cpp/test.cpp
Warning [flymake-proc test.cpp]: deleted file /home/linarcx/temp/cpp/test_flymake.cpp
Warning [flymake test.cpp]: Disabling backend flymake-proc-legacy-flymake because (wrong-type-argument stringp t)
```

GDB Run Stderr:
```
(node:2960) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

Process GDB::Run stderr finished
```
Warning:

> Warning (emacs): Initialize request failed: Failed to load MI Debugger: /home/linarcx/temp/cpp/~/temp/cpp/test.cpp: No such file or directory. (from file-exec-and-symbols "/home/linarcx/temp/cpp/~/temp/cpp/test.cpp")

clangd-stderr:

```
I[20:23:06.750] <-- initialize(1)
I[20:23:06.750] --> reply:initialize(1) 0 ms
I[20:23:06.878] <-- initialized
I[20:23:06.878] unhandled notification initialized
I[20:23:06.879] <-- textDocument/didOpen
I[20:23:06.880] Failed to find compilation database for /home/linarcx/temp/cpp/test.cpp
I[20:23:06.880] Updating file /home/linarcx/temp/cpp/test.cpp with command [/home/linarcx/temp/cpp] /usr/bin/clang /home/linarcx/temp/cpp/test.cpp
I[20:23:07.073] <-- textDocument/codeAction(2)
I[20:23:07.073] --> reply:textDocument/codeAction(2) 0 ms
I[20:23:07.074] <-- textDocument/hover(3)
I[20:23:07.223] --> textDocument/publishDiagnostics
I[20:23:07.223] --> reply:textDocument/hover(3) 148 ms
I[20:23:07.238] <-- textDocument/codeAction(4)
I[20:23:07.238] --> reply:textDocument/codeAction(4) 0 ms
I[20:23:07.239] <-- textDocument/hover(5)
I[20:23:07.239] --> reply:textDocument/hover(5) 0 ms
I[20:23:12.160] <-- textDocument/codeAction(6)
I[20:23:12.160] --> reply:textDocument/codeAction(6) 0 ms
I[20:23:12.162] <-- textDocument/hover(7)
I[20:23:12.162] --> reply:textDocument/hover(7) 0 ms
I[20:23:12.164] <-- textDocument/hover(8)
I[20:23:12.164] --> reply:textDocument/hover(8) 0 ms
I[20:23:12.166] <-- textDocument/hover(9)
I[20:23:12.166] --> reply:textDocument/hover(9) 0 ms
I[20:23:12.167] <-- textDocument/hover(10)
I[20:23:12.167] --> reply:textDocument/hover(10) 0 ms
I[20:23:12.169] <-- textDocument/hover(11)
I[20:23:12.169] --> reply:textDocument/hover(11) 0 ms
I[20:23:12.170] <-- textDocument/hover(12)
I[20:23:12.171] --> reply:textDocument/hover(12) 0 ms
I[20:23:12.172] <-- textDocument/hover(13)
I[20:23:12.172] --> reply:textDocument/hover(13) 0 ms
I[20:23:13.020] <-- textDocument/hover(14)
I[20:23:13.021] --> reply:textDocument/hover(14) 0 ms
I[20:23:13.032] <-- textDocument/hover(15)
I[20:23:13.032] --> reply:textDocument/hover(15) 0 ms
I[20:23:13.092] <-- textDocument/hover(16)
I[20:23:13.092] --> reply:textDocument/hover(16) 0 ms
I[20:23:13.304] <-- textDocument/codeAction(17)
I[20:23:13.304] --> reply:textDocument/codeAction(17) 0 ms
I[20:23:13.306] <-- textDocument/hover(18)
I[20:23:13.306] --> reply:textDocument/hover(18) 0 ms
I[20:23:13.307] <-- textDocument/hover(19)
I[20:23:13.308] --> reply:textDocument/hover(19) 0 ms
I[20:23:13.309] <-- textDocument/hover(20)
I[20:23:13.309] --> reply:textDocument/hover(20) 0 ms
I[20:23:13.311] <-- textDocument/documentHighlight(21)
I[20:23:13.311] --> reply:textDocument/documentHighlight(21) 0 ms
I[20:23:13.602] <-- textDocument/hover(22)
I[20:23:13.602] --> reply:textDocument/hover(22) 0 ms
I[20:23:13.603] <-- textDocument/signatureHelp(23)
I[20:23:13.609] --> reply:textDocument/signatureHelp(23) 6 ms
I[20:23:13.852] <-- textDocument/hover(24)
I[20:23:13.852] --> reply:textDocument/hover(24) 0 ms
I[20:23:16.069] <-- textDocument/codeAction(25)
I[20:23:16.069] --> reply:textDocument/codeAction(25) 0 ms
I[20:23:16.071] <-- textDocument/hover(26)
I[20:23:16.071] --> reply:textDocument/hover(26) 0 ms
I[20:23:16.072] <-- textDocument/hover(27)
I[20:23:16.072] --> reply:textDocument/hover(27) 0 ms
I[20:23:16.073] <-- textDocument/hover(28)
I[20:23:16.073] --> reply:textDocument/hover(28) 0 ms
I[20:23:16.134] <-- textDocument/hover(29)
I[20:23:16.134] --> reply:textDocument/hover(29) 0 ms
I[20:23:16.135] <-- textDocument/hover(30)
I[20:23:16.135] --> reply:textDocument/hover(30) 0 ms
I[20:23:16.135] <-- textDocument/hover(31)
I[20:23:16.135] --> reply:textDocument/hover(31) 0 ms
I[20:23:16.136] <-- textDocument/hover(32)
I[20:23:16.136] --> reply:textDocument/hover(32) 0 ms
I[20:23:16.368] <-- textDocument/hover(33)
I[20:23:16.368] --> reply:textDocument/hover(33) 0 ms
I[20:23:16.369] <-- textDocument/signatureHelp(34)
I[20:23:16.377] --> reply:textDocument/signatureHelp(34) 8 ms
I[20:26:19.264] <-- textDocument/hover(35)
I[20:26:19.264] --> reply:textDocument/hover(35) 0 ms
I[20:26:19.266] <-- textDocument/signatureHelp(36)
I[20:26:19.276] --> reply:textDocument/signatureHelp(36) 9 ms
I[20:29:31.258] <-- textDocument/hover(37)
I[20:29:31.258] --> reply:textDocument/hover(37) 0 ms
I[20:29:31.260] <-- textDocument/signatureHelp(38)
I[20:29:31.268] --> reply:textDocument/signatureHelp(38) 8 ms

```

**Comment by yyoncho** [comment] 2019-04-29 16:12
Do you have gdb-mi installed?

**Comment by yyoncho** [comment] 2019-04-29 16:16
Actually, if you have tried lldb debugger you should have lldb-mi on the path.

**Comment by LinArcX** [comment] 2019-04-29 16:29
There is no gdb-mi package in my distro repos(Arch linux).
I try to use lldb instead of gdb, but i get these errors:

```
safe(), or Buffer.from() methods instead.
(node:24135) UnhandledPromiseRejectionWarning
(node:24135) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24135) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yyoncho** [comment] 2019-04-29 17:00
Where do you get these errors? Also, can you enable the logging via setting dap-print-io to t.

**Comment by LinArcX** [comment] 2019-05-01 10:05
@yyoncho THere is no `dap-print-io`.
I create a simple c++ project. then run: `<M-x> dap-debug` and then select: `LLDB Run configuration` and then select `test.cpp` file as: __file to debug__ option.

**Comment by yyoncho** [comment] 2019-05-01 10:23
You should select a binary which is compiled with debug symbols.

**Comment by LinArcX** [comment] 2019-05-01 10:30
Yeah it's work but when i want to step into functions with, `dap-step-in`:
```
Running executable
Error opening terminal: unknown.
```

**Comment by yyoncho** [comment] 2019-05-01 12:29
I cannot help without steps to reproduce and logs, no sample project, etc. The only thing that I could answer to your query is "works for me". 

> @yyoncho There is no `dap-print-io`.

here it is https://github.com/emacs-lsp/dap-mode/blob/master/dap-mode.el#L39

**Comment by yyoncho** [comment] 2019-10-19 18:03
Closing - see https://github.com/emacs-lsp/dap-mode/issues/80#issuecomment-488270516

**Closed by yyoncho** 2019-10-19 18:03 UTC
