### ISSUE TITLE
Cannot see go map in local variables

### ISSUE THREAD

**Issue by ezaquarii** [emacs-lsp/dap-mode#399] opened 2020-11-04 00:42 UTC
When debugging golang app and expanding local map variable, the following message is shown:

```
Wrong type argument: hash-table-p, nil
```

Map is not expanded. Viewing lists and channels work ok.

**Comment by ezaquarii** [comment] 2020-11-04 02:10
Here is a stacktrace obtained via `debug-on-error`: 
```
Debugger entered--Lisp error: (wrong-type-argument hash-table-p nil)
  gethash("value" nil)
  #f(compiled-function (input0) #<bytecode 0x275b8cd>)(nil)
  mapcar(#f(compiled-function (input0) #<bytecode 0x275b8cd>) (#<hash-table equal 4/65 0x229d541> nil #<hash-table equal 4/65 0x229d561> nil))
  -map(#f(compiled-function (input0) #<bytecode 0x275b8cd>) (#<hash-table equal 4/65 0x229d541> nil #<hash-table equal 4/65 0x229d561> nil))
  dap-ui-render-variables(#s(dap--debug-session :name "Launch File<1>" :last-id 11 :proc #<process Launch File<1>> :response-handlers #<hash-table eql 0/65 0x29134a5> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Launch File<1> out*> :thread-id 1 :workspace nil :threads nil :thread-states #<hash-table eql 1/65 0x29134c5> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x2d3f311> :cursor-marker nil :state running :breakpoints #<hash-table equal 2/65 0x29134e5> :thread-stack-frames #<hash-table eql 1/65 0x2923bcd> :launch-args (:type "go" :cwd "/home/tn/go/src/github.com/ezaquarii/pagerd" :request "launch" :name "Launch File<1>" :mode "debug" :program "/home/tn/go/src/github.com/ezaquarii/pagerd/cmd/pagerd/main.go" :buildFlags "" :args ("spooler") :env "" :envFile "" :dap-server-path ("node" "/home/tn/.emacs.d/.extension/vscode/golang.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/home/tn/go/bin/dlv" :packagePathToGoModPathMap #<hash-table equal 1/65 0x291311d>) :initialize-result #<hash-table equal 6/65 0x1375ad5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x29237cd> :output-displayed t) 1004 (:label #("h: <map[string]int> (length: 2)" 0 1 (face font-lock-variable-name-face) 3 31 (help-echo "<map[string]int> (length: 2)")) :icon dap-variable :value "<map[string]int> (length: 2)" :session #s(dap--debug-session :name "Launch File<1>" :last-id 11 :proc #<process Launch File<1>> :response-handlers #<hash-table eql 0/65 0x29134a5> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Launch File<1> out*> :thread-id 1 :workspace nil :threads nil :thread-states #<hash-table eql 1/65 0x29134c5> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x2d3f311> :cursor-marker nil :state running :breakpoints #<hash-table equal 2/65 0x29134e5> :thread-stack-frames #<hash-table eql 1/65 0x2923bcd> :launch-args (:type "go" :cwd "/home/tn/go/src/github.com/ezaquarii/pagerd" :request "launch" :name "Launch File<1>" :mode "debug" :program "/home/tn/go/src/github.com/ezaquarii/pagerd/cmd/pagerd/main.go" :buildFlags "" :args ("spooler") :env "" :envFile "" :dap-server-path ("node" "/home/tn/.emacs.d/.extension/vscode/golang.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/home/tn/go/bin/dlv" :packagePathToGoModPathMap #<hash-table equal 1/65 0x291311d>) :initialize-result #<hash-table equal 6/65 0x1375ad5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x29237cd> :output-displayed t) :variables-reference 1004 :name "h" :actions (quote (["Set value" dap-ui-set-variable-value])) :key "h" :children #f(compiled-function (&rest args2) #<bytecode 0x2d82b19>)))
  apply(dap-ui-render-variables (#s(dap--debug-session :name "Launch File<1>" :last-id 11 :proc #<process Launch File<1>> :response-handlers #<hash-table eql 0/65 0x29134a5> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Launch File<1> out*> :thread-id 1 :workspace nil :threads nil :thread-states #<hash-table eql 1/65 0x29134c5> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x2d3f311> :cursor-marker nil :state running :breakpoints #<hash-table equal 2/65 0x29134e5> :thread-stack-frames #<hash-table eql 1/65 0x2923bcd> :launch-args (:type "go" :cwd "/home/tn/go/src/github.com/ezaquarii/pagerd" :request "launch" :name "Launch File<1>" :mode "debug" :program "/home/tn/go/src/github.com/ezaquarii/pagerd/cmd/pagerd/main.go" :buildFlags "" :args ("spooler") :env "" :envFile "" :dap-server-path ("node" "/home/tn/.emacs.d/.extension/vscode/golang.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/home/tn/go/bin/dlv" :packagePathToGoModPathMap #<hash-table equal 1/65 0x291311d>) :initialize-result #<hash-table equal 6/65 0x1375ad5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x29237cd> :output-displayed t) 1004 (:label #("h: <map[string]int> (length: 2)" 0 1 (face font-lock-variable-name-face) 3 31 (help-echo "<map[string]int> (length: 2)")) :icon dap-variable :value "<map[string]int> (length: 2)" :session #s(dap--debug-session :name "Launch File<1>" :last-id 11 :proc #<process Launch File<1>> :response-handlers #<hash-table eql 0/65 0x29134a5> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Launch File<1> out*> :thread-id 1 :workspace nil :threads nil :thread-states #<hash-table eql 1/65 0x29134c5> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x2d3f311> :cursor-marker nil :state running :breakpoints #<hash-table equal 2/65 0x29134e5> :thread-stack-frames #<hash-table eql 1/65 0x2923bcd> :launch-args (:type "go" :cwd "/home/tn/go/src/github.com/ezaquarii/pagerd" :request "launch" :name "Launch File<1>" :mode "debug" :program "/home/tn/go/src/github.com/ezaquarii/pagerd/cmd/pagerd/main.go" :buildFlags "" :args ("spooler") :env "" :envFile "" :dap-server-path ("node" "/home/tn/.emacs.d/.extension/vscode/golang.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/home/tn/go/bin/dlv" :packagePathToGoModPathMap #<hash-table equal 1/65 0x291311d>) :initialize-result #<hash-table equal 6/65 0x1375ad5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x29237cd> :output-displayed t) :variables-reference 1004 :name "h" :actions (quote (["Set value" dap-ui-set-variable-value])) :key "h" :children #f(compiled-function (&rest args2) #<bytecode 0x2d82b19>))))
  #f(compiled-function (&rest args2) #<bytecode 0x2d82b19>)((:label #("h: <map[string]int> (length: 2)" 0 1 (face font-lock-variable-name-face) 3 31 (help-echo "<map[string]int> (length: 2)")) :icon dap-variable :value "<map[string]int> (length: 2)" :session #s(dap--debug-session :name "Launch File<1>" :last-id 11 :proc #<process Launch File<1>> :response-handlers #<hash-table eql 0/65 0x29134a5> :parser #s(dap--parser :waiting-for-response nil :response-result nil :headers nil :body nil :reading-body nil :body-length nil :body-received nil :leftovers "") :output-buffer #<buffer *Launch File<1> out*> :thread-id 1 :workspace nil :threads nil :thread-states #<hash-table eql 1/65 0x29134c5> :active-frame-id nil :active-frame #<hash-table equal 5/65 0x2d3f311> :cursor-marker nil :state running :breakpoints #<hash-table equal 2/65 0x29134e5> :thread-stack-frames #<hash-table eql 1/65 0x2923bcd> :launch-args (:type "go" :cwd "/home/tn/go/src/github.com/ezaquarii/pagerd" :request "launch" :name "Launch File<1>" :mode "debug" :program "/home/tn/go/src/github.com/ezaquarii/pagerd/cmd/pagerd/main.go" :buildFlags "" :args ("spooler") :env "" :envFile "" :dap-server-path ("node" "/home/tn/.emacs.d/.extension/vscode/golang.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/home/tn/go/bin/dlv" :packagePathToGoModPathMap #<hash-table equal 1/65 0x291311d>) :initialize-result #<hash-table equal 6/65 0x1375ad5> :error-message nil :loaded-sources nil :program-proc nil :metadata #<hash-table eql 0/65 0x29237cd> :output-displayed t) :variables-reference 1004 :name "h" :actions (quote (["Set value" dap-ui-set-variable-value])) :key "h" :children #f(compiled-function (&rest args2) #<bytecode 0x2d82b19>)))
  treemacs--do-expand-node(#<marker (moves after insertion) at 168 in *dap-ui-locals*>)
  treemacs-expand-node(nil)
  treemacs-TAB-action(nil)
  funcall-interactively(treemacs-TAB-action nil)
  call-interactively(treemacs-TAB-action nil nil)
  command-execute(treemacs-TAB-action)
```

**Comment by nbfalcon** [comment] 2020-11-04 07:44
I cannot reproduce with debugpy - are you using the latest version of dap-mode?

**Comment by ezaquarii** [comment] 2020-11-04 20:51
If I read the google correctly, `debugpy` is Python? I'm debugging `go`.

Yes, I tried newest version from melpa.

**Comment by ezaquarii** [comment] 2020-11-04 21:01
@nbfalcon Is there anything I can do to help you reproduce this problem? Maybe there is some debug procedure I could do locally on my machine? Sadly, I'm not familiar with elisp to pinpoint the problem, but with some guidance I should be able to get something more specific.

**Comment by yyoncho** [comment] 2020-11-04 21:21
providing the server logs will help. Set dap-print-io and then observe Messages buffer trying to find the response that causes the error.

**Comment by nbfalcon** [comment] 2020-11-05 08:09
@ezaquarii do `M-x trace-function RET dap-ui-render-variables` and debug, then show me the trace. (You can undo the effects using `M-x untrace-function`).

**Comment by ezaquarii** [comment] 2020-11-08 01:57
@nbfalcon 
Here is the output. I tried to display Go type `map[string]string`.

```
=====================================
1 -> (dap-ui-render-variables #5=#s(dap--debug-session #2="Launch File<2>" 13 #<process Launch File<2>> #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data ()) #s(dap--parser nil nil nil nil nil nil nil "") #<buffer *Launch File<2> out*> 34 nil nil #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data (34 "breakpoint")) nil #1=#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 1000 "source" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("name" "config_test.go" "path" "/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/config/config_test.go" "sourceReference" 0)) "line" 143 "column" 0 "name" "github.com/ezaquarii/pagerd/pkg/config.TestReadConfigEnv.func2")) nil running #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/cmds/spooler.go" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" nil "line" 18))) "/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/server/client_test.go" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" nil "line" 183))) "/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/nextcloud/app.go" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" nil "line" 47))) "/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/app/flags_test.go" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" nil "line" 13)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" nil "line" 51)) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" nil "line" 51))) #3="/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/config/config_test.go" (#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("verified" t "line" 143))))) #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data (34 (#1# #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 1001 "source" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("name" "testing.go" "path" "/usr/lib/go-1.13/src/testing/testing.go" "sourceReference" 0)) "line" 909 "column" 0 "name" "testing.tRunner")) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 1002 "source" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("name" "asm_amd64.s" "path" "/usr/lib/go-1.13/src/runtime/asm_amd64.s" "sourceReference" 0)) "line" 1357 "column" 0 "name" "runtime.goexit"))))) (:type "go" :request "launch" :name #2# :mode "test" :program #3# :buildFlags nil :args nil :env nil :envFile nil :dap-server-path ("node" "/home/tn/.emacs.d/.extension/vscode/golang.go/extension/out/src/debugAdapter/goDebug.js") :dlvToolPath "/home/tn/go/bin/dlv" :packagePathToGoModPathMap #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("/home/tn/go/src/github.com/ezaquarii/pagerd/pkg/config" "/home/tn/go/src/github.com/ezaquarii/pagerd"))) #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("seq" 1 "type" "response" "request_seq" 1 "command" "initialize" "success" t "body" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("supportsConfigurationDoneRequest" t "supportsSetVariable" t)))) nil nil nil #s(hash-table size 65 test eql rehash-size 1.5 rehash-threshold 0.8125 data ()) t) 1003 (:label #("configEnv: <map[string]string> (length..." 0 9 (face font-lock-variable-name-face) 11 41 (help-echo #4="<map[string]string> (length: 7091318039310988591)")) :icon dap-variable :value #4# :session #5# :variables-reference 1003 :name #6="configEnv" :actions (quote (["Set value" dap-ui-set-variable-value])) :key #6# :children #[128 "\302\300\303\301\"\"\207" [dap-ui-render-variables (#5# 1003) apply append] 6 "

(fn &rest ARGS2)"]))
1 <- dap-ui-render-variables: nil
```

I'm not sure how to pretty-print the trace.

**Comment by ezaquarii** [comment] 2020-11-08 01:59
@yyoncho I think this is what I get in the `*messages*` buffer:

```
Sending: 
{
  "command": "variables",
  "arguments": {
    "variablesReference": 1003
  },
  "type": "request",
  "seq": 16
}
Received:
{
  "body": {
    "variables": null
  },
  "success": true,
  "command": "variables",
  "request_seq": 16,
  "type": "response",
  "seq": 19
}
```

**Comment by nbfalcon** [comment] 2020-11-10 16:51
It's a protocol violation by the go debug adapter (variables shall not be null, at most an empty array), but we may still handle it.

**Comment by nbfalcon** [comment] 2020-11-10 16:52
However, it should still work: -map over nil should be a no-op.

**Comment by nbfalcon** [comment] 2020-11-10 16:54
@ezaquarii could you point me to a go project that I could try this on? I am sadly not a go programmer myself, and I'd need to debug this further.

**Comment by ezaquarii** [comment] 2020-11-30 00:05
@nbfalcon Sorry that it took me so long.

Here is a minimum reproduction case:
https://github.com/ezaquarii/issue399

it contains a simple hello world and a minimal emacs config for go. Just drop emacs.d to your `$HOME/emacs.d` and run the `M-x` stuff as enumerated in `main.go` file.

You'll need a go compiler and debugger. I provided a `Makefile` that installs the debugger.

**Comment by ezaquarii** [comment] 2020-11-30 00:07
@nbfalcon I suspect that `delve` has buggy `DAP` protocol implementation. If all we get from this analysis is what is missing, we might be able to open an actionable bug report in `delve` project. I don't know `dap` protocol so I'm not sure what is missing there.

**Comment by ezaquarii** [comment] 2020-11-30 00:08
@nbfalcon @yyoncho  I suspect that delve has buggy DAP protocol implementation. If all we get from this analysis is what is missing, we might be able to open an actionable bug report in delve project. I don't know dap protocol so I'm not sure what is missing there.

**Comment by fgeller** [comment] 2020-12-17 18:57
hey @yyoncho @nbfalcon  - i'm seeing this issue as well. just tested it against
```
dap-mode           20201118.1304

$ dlv version
Delve Debugger
Version: 1.5.1
Build: 8221250e6502a274898db5228afaef4bf6770b74
```

After setting `dap-print-io`, this is the output to `*Messages*` when inspecting a map variable.

```
Sending: 
{
  "command": "variables",
  "arguments": {
    "variablesReference": 1004
  },
  "type": "request",
  "seq": 9
}
Received:
{
  "body": {
    "variables": [
      {
        "variablesReference": 1006,
        "evaluateName": "fn2is[\"route\"]",
        "value": "<map[int]bool> (length: 16)",
        "name": "\"route\""
      },
      null,
-------------------------[ snip ]--------------------------------------
      {
        "variablesReference": 1025,
        "evaluateName": "fn2is[\"departure location\"]",
        "value": "<map[int]bool> (length: 7)",
        "name": "\"departure location\""
      },
      null
    ]
  },
  "success": true,
  "command": "variables",
  "request_seq": 9,
  "type": "response",
  "seq": 14
}
Wrong type argument: hash-table-p, nil
```

I'm guessing the `null` is the issue? Not sure if it helps, but they seem to be redundant entries, I can see all the contents of the map (even though I cropped it from this snippet).

Is there a way for me to provide more details that would help or could you point me roughly in the right direction of where I could start reading Emacs Lisp so that I could try to help out?

Other than this issue it was a pleasure to set this up and be able to use a source level debugger for Go in Emacs -- thanks! 🙏

**Comment by nbfalcon** [comment] 2021-01-01 15:20
Can you please check out my workaround branch and see if the issue persists? Also, what are the "nulls" supposed to represent? Do you have actual "nulls" in your maps, or is ignoring them enough? I'd be great to fix this upstream.

**Comment by ezaquarii** [comment] 2021-01-02 12:12
@nbfalcon I had this issue with map that did not have any nulls in it:
https://github.com/ezaquarii/issue399/blob/master/main.go
This example has a `map[string]string` with non-nil keys and values.

I'll check your workaround.

Can you elaborate a bit how DLV is violating the specification, so we can file an upstream issue?

**Comment by ezaquarii** [comment] 2021-01-02 12:15
@nbfalcon 
> Can you please check out my workaround branch and see if the issue persists?

I'll check your workaround.

> Also, what are the "nulls" supposed to represent?

In Go, they are NULL pointers basically, like in C/C++ or Java.

> Do you have actual "nulls" in your maps, or is ignoring them enough?

https://github.com/ezaquarii/issue399/blob/master/main.go
This example has a map[string]string with non-nil keys and values, so the answer is "no, I don't have any nulls in the map".

> I'd be great to fix this upstream.

Can you elaborate a bit how DLV is violating the specification, so we can file an upstream issue?

**Comment by ezaquarii** [comment] 2021-01-03 12:40
@nbfalcon 
> Do you have actual "nulls" in your maps, or is ignoring them enough?

If I understand you correctly, are you asking if the map can contain genuine null values? The anwer to that would be yes, you can have a `map[string]*Foo` for example, which is map from string to a pointer to `Foo`.  In such case, the map can certainly contain `nil` values. The same applies for keys.

Does your fix work in such scenarios?

**Comment by ezaquarii** [comment] 2021-01-27 02:06
@nbfalcon I can confirm that your workaround works very well. 
If works with `nil` keys as well as `nil` values.

I'd merge this PR and on top of that, I'm keen on taking this issue upstream to fix DAP protocol in Delve.

**Comment by ezaquarii** [comment] 2021-02-22 22:59
@nbfalcon can we merge it and have it in MELPA?

**Comment by nbfalcon** [comment] 2021-02-23 12:31
@ezaquarii I don't think this should be merged, as it is a workaround; rather, this should be taken upstream. I was able to reproduce this and to get a proper output response, and I'll be opening an issue on `delve's` github soon.

**Comment by nbfalcon** [comment] 2021-02-23 12:35
On second thought, this may be a bug in `vscode-go`, which could be resolved by implenting `dlvdap` support directly.

**Comment by nbfalcon** [comment] 2021-02-23 13:06
This bug is fixed in the latest version of `vscode-go`, and bumping its version fixes this. I'll be making a PR soon.

**Closed** 2021-05-06 19:34 UTC

**Comment by nbfalcon** [comment] 2021-05-06 19:36
Sorry for the delay, this bug is now fixed in latest master. All you need to is to update dap-mode, and then execute `C-u M-x dap-go-setup`:
![20210506-213553](https://user-images.githubusercontent.com/69264154/117355587-15059b00-aeb3-11eb-892d-25fe95052b73.png)
