### ISSUE TITLE
(error "Hash table data is not a list of even length") after update

### ISSUE THREAD

**Issue by CsBigDataHub** [emacs-lsp/dap-mode#368] opened 2020-09-21 23:18 UTC
error at init - `Failed to load breakpoints for the current workspace with error: (error "Hash table data is not a list of even length")`

error when initializing lsp-mode - `Error running timer: (wrong-type-argument hash-table-p nil)`

I have re-compiled entire elpa folder with

```
(progn (package-refresh-contents)
    (package-install-selected-packages)
    (byte-recompile-directory package-user-dir nil 'force))
```

 yet I still get this error.

**Comment by CsBigDataHub** [comment] 2020-09-22 14:20
I am posting work-around for travellers.

delete `~/.emacs.d/.dap-breakpoints` file and restart emacs.

Thanks @yyoncho , I will keep this issue open to investigate why this error occurs all of a sudden.

**Comment by nbfalcon** [comment] 2020-09-22 14:22
I noticed this strange issue too. Perhaps it has to do with dap being updated and data-structures changing?

**Comment by nbfalcon** [comment] 2020-09-22 14:23
@CsBigDataHub do you have your original .dap-breakpoints file somewhere laying around?

**Comment by CsBigDataHub** [comment] 2020-09-22 15:53
> @CsBigDataHub do you have your original .dap-breakpoints file somewhere laying around?

Nope, deleted it this morning. Sorry

**Comment by nbfalcon** [comment] 2020-09-22 16:15
Okay, so if anyone encounters this, please post your .dap-breakpoints file before deleting it.

**Comment by yyoncho** [comment] 2020-09-22 20:41
> I noticed this strange issue too. Perhaps it has to do with dap being updated and data-structures changing?

The breakpoints related code is messy(it is the first elisp code I wrote in my life). The issue is that somehow in the .dap-breakpoints end up `nil` entry. But generally, the breakpoints code should be revisited.

**Comment by nbfalcon** [comment] 2020-11-03 14:23
This is probably not a problem with dap-mode, as it implies that a hash-table was incorrectly written, which cannot be the case as dap-mode uses the built-in Emacs Lisp printer functions. Maybe this was caused because you killed Emacs in the middle of a breakpoint write? AFAICS, dap use `with-temp-file` for writing breakpoints, which is interrupt-atomic. I don't believe we can do anything here, so I'm closing.

**Closed by nbfalcon** 2020-11-03 14:23 UTC

**Comment by Silipwn** [comment] 2021-07-29 04:36
Hi,
Was facing this same issue.

Here's a sample if it helps
```
#s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8125 data ( ...))
```
(This is the entire content of the file)

The hash table data error causes many other issues for me as well, from different packages, any pointers on how to debug this further?
