### ISSUE TITLE
"Java Run Configuration (compile/attach)" template shows error

### ISSUE THREAD

**Issue by pavilion** [emacs-lsp/dap-mode#102] opened 2019-07-06 12:10 UTC
When I select the main class to run, I get 
`lsp-request: com.google.gson.JsonPrimitive cannot be cast to java.lang.String`

**Comment by yyoncho** [comment] 2019-07-06 13:01
I am unable to reproduce, can you provide lsp logs? You could do that by setting lsp-print-io to t and then using lsp-workspace-log to go the the server log.

**Comment by yyoncho** [comment] 2019-07-06 13:02
Also, before we continue, please make sure that you are using latest lsp packages and latest server components.

**Comment by pavilion** [comment] 2019-07-06 14:43
What package provides `lsp-print-io`? And yes, I am using latest lsp-java and did a `lsp-java-update-server` after installing `dap-mode`

**Comment by yyoncho** [comment] 2019-07-06 14:58
It is from lsp-mode. You should do `(setq lsp-print-io t)` or M-x customize-variable

**Comment by pavilion** [comment] 2019-07-06 15:03
instead of `lsp-workspace-log` you mean `lsp-workspace-show-log` right?

**Comment by pavilion** [comment] 2019-07-06 15:06
Here is the log from when I open the project until I do `dap-debug` and select `Java Run Configuration`

https://gist.github.com/pavilion/7df635e7658d6f4f94e48774d684c7ca

**Comment by yyoncho** [comment] 2019-07-06 15:44
It was me that wasn't running with the latest server. IMO latest jdt ls has broken the debug plugin but I had to investigate more.

To workaround the issue do:

```
(setq lsp-java-jdt-download-url "http://download.eclipse.org/jdtls/milestones/0.40.0/jdt-language-server-0.40.0-201906040221.tar.gz")
```
and then `M-x` `lsp-java-update-server`

This will download a working version of  the server. You will probably need to delete the workspace(it is located in ~/.emacs.d/workspace . Let me know if it works.

**Comment by yyoncho** [comment] 2019-07-06 15:59
@testforstephen It looks like the latest jdt ls is incompatible with java debug extension(I think after bump of lsp4j).

here it is what we have in the logs 

```
[Trace - 04:04:49 pm] Sending request 'workspace/executeCommand - (5)'.
Params: {
  "command": "vscode.java.resolveClasspath",
  "arguments": [
    "com.example.demo.DemoApplication",
    "demo"
  ]
}
```

```
06-Jul-2019 16:04:49 Error in calling delegate command handler
com.google.gson.JsonPrimitive cannot be cast to java.lang.String
java.lang.ClassCastException: com.google.gson.JsonPrimitive cannot be cast to java.lang.String
	at com.microsoft.java.debug.plugin.internal.ResolveClasspathsHandler.resolveClasspaths(ResolveClasspathsHandler.java:47)
	at com.microsoft.java.debug.plugin.internal.JavaDebugDelegateCommandHandler.executeCommand(JavaDebugDelegateCommandHandler.java:43)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:206)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:196)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:451)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$40(JDTLanguageServer.java:892)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by testforstephen** [comment] 2019-07-08 04:41
thanks let me know. i'll have a look.

**Comment by testforstephen** [comment] 2019-07-08 12:09
it is fixed in the eclipse.jdt.ls, you can download the latest jdt.ls build to have a try.

**Comment by yyoncho** [comment] 2019-07-08 16:27
@testforstephen thank you, it works fine now.

**Closed by yyoncho** 2019-07-08 16:27 UTC
