### ISSUE TITLE
How to disable dap-ui-controls in terminal?

### ISSUE THREAD

**Issue by ztlevi** [emacs-lsp/dap-mode#409] opened 2020-11-17 02:02 UTC
Hi,

I'm trying to use dap-mode in terminal but couldn't figure out the proper way to disable dap-ui-controls-mode.

I tried remove `controls` form `dap-auto-configure-features` but no luck. There is also a const called `dap-features->modes` which might cause the dap-mode to call dap-ui-controls in the terminal.

What's the proper way to disable dap-ui-contorls in terminal?

Thanks

**Comment by nbfalcon** [comment] 2020-12-02 18:19
You'll need to remove `controls` before `dap-auto-configure-features` is called. Try restarting Emacs and then removing it, without starting a debug session first. `dap-features->modes` doesn't itself cause anything to be shown, and it shouldn't be user-visible; it maps `dap-auto-configure-features` to the modes responsible for them.

**Comment by ztlevi** [comment] 2020-12-02 19:16
@nbfalcon Thanks for the help! 

I tried `(setq lsp-enable-dap-auto-configure nil)` and
```  
(when (not (display-graphic-p))
    (setq dap-auto-configure-features '(sessions locals expressions)))
```
But no luck.

What's the correct way to remove controls from `dap-auto-configure-features`? Also, it would be ideal for `controls` component to be disabled by default in terminal.

Here is the error message and the backtrace:
```
error in process filter: dap-ui--update-controls: Wrong type argument: framep, nil
error in process filter: Wrong type argument: framep, nil
error in process filter: dap-ui--update-controls: Wrong type argument: framep, nil
error in process filter: Wrong type argument: framep, nil
```

```
  select-frame(nil)
  dap-ui--update-controls()
  run-hook-with-args(dap-ui--update-controls)
  #f(compiled-function (_) #<bytecode 0x1ffd35f28fe5>)(#<hash-table equal 7/65 0x1ffd362c1871>)
  #f(compiled-function (input0) #<bytecode 0x1ffd362c16bd>)(#<hash-table equal 7/65 0x1ffd362c1871>)
  #f(compiled-function (m) #<bytecode 0x1ffd362c1841>)("{\"type\": \"response\", \"seq\": 8, \"request_seq\": 6, \"...")
  mapc(#f(compiled-function (m) #<bytecode 0x1ffd362c1841>) ("{\"type\": \"response\", \"seq\": 8, \"request_seq\": 6, \"..."))
  #f(compiled-function (_ msg) #<bytecode 0x1ffd35e410e9>)(#<process Python :: Run file (buffer)> "Content-Length: 124\15\n\15\n{\"type\": \"response\", \"seq\":...")
```

**Comment by nbfalcon** [comment] 2020-12-03 07:27
I'll just offer an advice hack for now:
```emacs-lisp
(when (*in-terminal-p*) (eval-after-load 'lsp-mode '(advice-add 'dap-ui-controls-mode :override #'ignore)))

Don't close this, as this is not actually solved in an elegant way.

**Comment by ztlevi** [comment] 2020-12-03 18:42
@nbfalcon It still raises error in terminal.
I'm using this config.

```
(when (not (display-graphic-p))
  (eval-after-load 'lsp-mode '(advice-add 'dap-ui-controls-mode :override #'ignore)))
```

```
error in process filter: dap-ui--update-controls: Wrong type argument: framep, nil
error in process filter: Wrong type argument: framep, nil
No message handler for process
error in process filter: dap-ui--update-controls: Wrong type argument: framep, nil
error in process filter: Wrong type argument: framep, nil
error in process filter: dap-ui--update-controls: Wrong type argument: framep, nil
error in process filter: Wrong type argument: framep, nil
error in process filter: ad-Advice-select-window: Wrong type argument: window-live-p, nil
error in process filter: Wrong type argument: window-live-p, nil
```

**Comment by nbfalcon** [comment] 2020-12-07 04:18
```emacs-lisp
(when (*in-terminal-p*) (eval-after-load 'lsp-mode '(advice-add 'dap-ui--update-controls :override #'ignore)))
```
more layers of hacks :)

**Comment by ztlevi** [comment] 2020-12-07 18:00
Thanks. this one works.

**Comment by BaoshanPang** [comment] 2021-02-05 18:42
> ```emacs-lisp
> (when (*in-terminal-p*) (eval-after-load 'lsp-mode '(advice-add 'dap-ui--update-controls :override #'ignore)))
> ```
> 
> more layers of hacks :)

Sorry if this is dumb question.
Where should I add this code?  I added it into my .emacs, but get this error:
Symbol's function definition is void: *in-terminal-p*

**Comment by ztlevi** [comment] 2021-02-05 23:05
@yyoncho What's the official way to disable that now?

**Comment by yyoncho** [comment] 2021-02-06 01:30
It should "just works".

**Closed by yyoncho** 2021-02-06 01:30 UTC

**Comment by BaoshanPang** [comment] 2021-02-06 22:31
Cool! With a package update, I see the issue is gone. Thanks for the quick fix. --Baoshan

**Comment by danielkrajnik** [comment] 2023-12-08 12:02
I still can't seem to get it to work:
```lisp
(after! dap-mode
  (setq dap-python-debugger 'debugpy)
  (setq dap-auto-configure-features '(locals tooltip))
  )
```
controls are still showing up: 
![image](https://github.com/emacs-lsp/dap-mode/assets/15096799/50b1130e-fda6-4566-bbd6-bbf77e037138)
